export const NAME_LIMIT = +process.env.NAME_LIMIT!
export const NAME_LIMIT_2 = +process.env.NAME_LIMIT_2!
export const TIME_LOAD_DELAY = 1_000
export const TIME_ALERT_2 = 2_000
export const TIME_ALERT_5 = 5_000

export enum C {
    LOADING = 'loading',
    REFRESH = 'refresh',

    // BASE
    ID = 'id',
    TARGET = 'target',
    ADMIN = 'admin',
    USER = 'user',
    GUEST = 'guest',
    USERS = 'users',
    LOGIN = 'login',
    PASSWORD = 'password',
    USERNAME = 'username',
    EMAIL = 'email',
    DATA = 'data',
    STATUS = 'status',
    MONITOR = 'monitor',
    ERROR = 'error',
    MESSAGE = 'message',
    DETAIL = 'detail',
    RESULT = 'result',
    PLACE = 'place',
    NAME = 'name',
    VALUE = 'value',
    SOURCE = 'source',
    DELETE = 'delete',
    DELETED = 'deleted',
    TIME = 'time',
    TIME_TAKEN = 'time_taken',
    DURATION = 'duration',
    TIME_PLAYED = 'timePlayed',
    DATETIME = 'datetime',
    ORDER = 'order',
    DATE = 'date',
    PAGE = 'page',
    PAGES = 'pages',
    EPOCH = 'epoch',
    ISO = 'iso',
    LOGS = 'logs',
    NOT_VALID = 'not valid',
    NOT_FOUND = 'not found',
    ALREADY_EXIST = 'already exist',
    YEAR = 'year',
    LANGUAGE = 'language',
    ROLE = 'role',
    ROLES = 'roles',
    LEVEL = 'level',
    STATS = 'stats',
    BASE = 'base',
    AUTO_UPDATE = 'auto_update',
    ACTIVE = 'active',
    INACTIVE = 'inactive',
    TOKEN = 'token',
    CONFIG = 'config',
    CONFIGS = 'configs',

    // languages
    EN = 'en-US',
    RU = 'ru-RU',

    // NOTES
    NOTE = 'note',
    NOTES = 'notes',
    UNCOMPLETED = 'uncompleted',

    // TRACKER

    // game modes
    ALL = 'all',
    MW_MP = 'mw_mp',
    MW_WZ = 'mw_wz',
    CW_MP = 'cw_mp',
    VG_MP = 'vg_mp',

    MW = 'mw',
    CW = 'cw',
    VG = 'vg',
    MP = 'mp',
    WZ = 'wz',

    // platform
    UNO = 'uno',
    ACTI = 'acti',
    BATTLE = 'battle',

    UNOS = 'unos',
    CLANTAG = 'clantag',
    GAMES = 'games',
    GAME = 'game',
    MAP = 'map',
    MODE = 'mode',
    GAME_MODE = 'game_mode',
    DATA_TYPE = 'data_type',
    PLAYER_TAG = 'player_tag',
    TARGET_TYPE = 'target_type',
    PLATFORM = 'platform',
    PLAYER = 'player',
    PLAYERS = 'players',
    GROUP = 'group',
    GROUPS = 'groups',
    UPDATE_PLAYERS = 'update_players',
    BASIC = 'basic',
    MAIN = 'main',
    MATCHID = 'matchID',
    MATCH = 'match',
    MATCHES = 'matches',
    MATCHES_HISTORY = 'matches_history',
    FULLMATCHES = 'fullmatches',
    FULLMATCHES_PARS = 'fullmatches_pars',
    KILLS = 'kills',
    DEATHS = 'deaths',
    KDRATIO = 'kdRatio',
    ACCURACY = 'accuracy',
    HEADSHOTS = 'headshots',
    USES = 'uses',
    SEARCH = 'search',
    SUMMARY = 'summary',
    TRACKER = 'tracker',
    LABEL = 'label',
    CHART = 'chart',
    MOST_PLAY_WITH = 'most_play_with',
    LOADOUT = 'loadout',
    GAMES_STATS = 'games_stats',
    TASK_QUEUES = 'task_queues',
    RAW = 'raw',
    PLAYED = 'played',
    COMPLETED = 'completed',
    TRANSLATE = 'translate',
    ENABLED = 'enabled',
    DISABLED = 'disabled',
    ROWS = 'rows',
    TEAM = 'team',
    STATIC = 'static',
    FILES = 'files',
    COUNT = 'count',
}
